---
name: Request something else
description: Have an idea for something else? Let us know here!
labels: other
body:
  - type: markdown
    attributes:
      value: |
        Firstly, thanks for taking the time to request something!
        Please ensure your request has not been raised before on [GitHub Issues](https://github.com/anipalur/gce-a-levels-bot/issues "Visit the GitHub Issues tab.").
        Duplicate or unrelated issues will be closed.
  - type: input
    id: discord-username
    attributes:
      label: Discord Username
      description: Please share your Discord username so we can get in touch with you
        for more information.
      value: Not specified.
  - type: textarea
    id: related-problem
    attributes:
      label: Related Problem
      description: Is an existing problem related to your request? If so, please
        describe it.
      value: I'm always frustrated when...
  - type: textarea
    id: request-description
    attributes:
      label: Request Description
      description: Describe your request.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to abide by our [Code of Conduct](https://github.com/anipalur/gce-a-levels-bot/blob/main/CODE_OF_CONDUCT.md "View the Code of Conduct.").
      options:
        - label: I agree to abide by the Code of Conduct.
          required: true
