# Checks if all .js and .md files have been linted correctly.
---
name: Lint
on:
  - pull_request
  - push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run is-linted:js
      - name: Run markdownlint
        run: npm run is-linted:md
